[project]
name = "bspricer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "playwright>=1.58.0",
    "plotly>=6.5.2",
    "streamlit>=1.54.0",
    "yfinance>=1.1.0",
]
