name: Keep Streamlit App Awake

on:
  schedule:
    - cron: '0 */10 * * *'  # evert 10 h
  workflow_dispatch:  # Allow manual triggering

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Make empty commit
        run: |
          git config --global user.name 'Zian Chen'
          git config --global user.email 'ziancn@hotmail.com'
          git commit --allow-empty -m "Empty commit to keep app awake"
          git push